### ISSUE TITLE
Use case : Ordering of the Coherency (T) Matrices

### ISSUE THREAD

**Issue by khanfarhan10** [avikcsre/SD_Y4O#1]
Hello @avikcsre , @Shaunakde , the repository doesnot state as to what should be the precise input for the UI widget tool in MATLAB.

In actuality it is not known whether we have to enter the matrices in this order (A) : 

`T11, T12_real, T12_imag, T13_real, T13_imag, T22, T23_real, T23_imag, T33`

Or the following order (B) :

`T11, T22,  T33, T12_real, T12_imag, T13_real, T13_imag, T23_real, T23_imag`

The readme clearly states to follow ordering A, but I do think that the MATLAB code implemented does B.

Please inform and rectify instructions in the README for the same.

P.S. - Thanks for the amazing Research Paper and the Code as well. Cheers to Programming & Remote Sensing.

**Comment by Shaunakde** [comment]
Thanks for opening this issue. You are right in that the `Readme` seems to be incorrect. 

Looking at the code [Here](https://github.com/avikcsre/SD_Y4O/blob/1cd213442e3eabc5c875a9759466cb1ab942b042/SD_Y4O_2.m#L29) is where the files are input, and [Here](https://github.com/avikcsre/SD_Y4O/blob/1cd213442e3eabc5c875a9759466cb1ab942b042/SD_Y4O_2.m#L77-L91) is where the T-matrix is formed. 

It looks like your assessment is spot-on, and I will open a MR to fix it.

**Comment by Shaunakde** [comment]
Fixed! Thank you @khanfarhan10

**Comment by khanfarhan10** [comment]
Welcome. Thanks for the code.
